// Angular/portfolio/src/app/form/form.component.ts
// form.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-form',
  templateUrl: './form.component.html',
  styleUrls: ['./form.component.css']
})
export class FormComponent {
  formData = {
    companyName: '',
    interviewDate: '',
    proposedPosition: '',
    email: '',
    companyWebsite: ''
  };

  handleChange(event: Event, name: string) {
    const value = (event.target as HTMLInputElement).value;
    this.formData = { ...this.formData, [name]: value } as typeof this.formData;
  }

  handleReset() {
    this.formData = {
      companyName: '',
      interviewDate: '',
      proposedPosition: '',
      email: '',
      companyWebsite: ''
    };
  }
}
<div class="backgroundMain">
    <div>
      <input
        class="formInput"
        type="text"
        placeholder=" Название компании"
        name="companyName"
        [(ngModel)]="formData.companyName"
      />
      <input
        class="formInput"
        type="text"
        placeholder=" Дата собеседования"
        name="interviewDate"
        [(ngModel)]="formData.interviewDate"
      />
      <input
        class="formInput"
        type="text"
        placeholder=" Предлагаемая должность"
        name="proposedPosition"
        [(ngModel)]="formData.proposedPosition"
      />
      <input
        class="formInput"
        type="text"
        placeholder=" Email"
        name="email"
        [(ngModel)]="formData.email"
      />
      <input
        class="formInput"
        type="text"
        placeholder=" Сайт компании"
        name="companyWebsite"
        [(ngModel)]="formData.companyWebsite"
      />
    </div>
    <div class="formDiv">
      <a type="button" class="HeaderButton" (click)="handleReset()">
        Отправить
      </a>
    </div>
  </div>

// Reacr/portfolio/src/Form/Form.tsx
import React, { useState } from 'react';

function Form() {
  const [formData, setFormData] = useState({
    companyName: '',
    interviewDate: '',
    proposedPosition: '',
    email: '',
    companyWebsite: ''
  });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    setFormData((prevData) => ({
      ...prevData,
      [name]: value
    }));
  };

  const handleReset = () => {
    setFormData({
      companyName: '',
      interviewDate: '',
      proposedPosition: '',
      email: '',
      companyWebsite: ''
    });
  };

  return (
    <div className="backgroundMain">
      <div>
        <input
          className='formInput'
          type="text"
          placeholder=' Название компании'
          name="companyName"
          value={formData.companyName}
          onChange={handleChange}
        />
        <input
          className='formInput'
          type="text"
          placeholder=' Дата собеседования'
          name="interviewDate"
          value={formData.interviewDate}
          onChange={handleChange}
        />
        <input
          className='formInput'
          type="text"
          placeholder=' Предлагаемая должность'
          name="proposedPosition"
          value={formData.proposedPosition}
          onChange={handleChange}
        />
        <input
          className='formInput'
          type="text"
          placeholder=' Email'
          name="email"
          value={formData.email}
          onChange={handleChange}
        />
        <input
          className='formInput'
          type="text"
          placeholder=' Сайт компании'
          name="companyWebsite"
          value={formData.companyWebsite}
          onChange={handleChange}
        />
      </div>
      <div className='formDiv'>
        <button type="button" className='HeaderButton' onClick={handleReset}>
          Отправить
        </button>
      </div>
    </div>
  );
}

export default Form;
