// Reacr/portfolio/src/Home/Home.tsx
import React from 'react'

function Home() {
  return (
    <div className="backgroundMain">
        <div className='homeDiv'>
          <img src='https://pic.rutubelist.ru/video/ec/0c/ec0c12ae7b425bd4055f9f0e16f3498e.jpg'></img>    
        </div>
        <div className='homeDiv'>
          <a className='HeaderButton' href='https://github.com/DmitriyGorbulko/Portfolio'>Ссылка на GitHub</a>
        </div>
        <div className='homeDiv'>
          <ul className='homeUl'>
            Навыки
            <li className='homeLi'>Принципы SOLID</li>
            <li className='homeLi'>Архитектура Onion</li>
            <li className='homeLi'>Работа с различными реляционными БД</li>
            <li className='homeLi'>Архитектура Onion</li>
            <li className='homeLi'>Стремление к изучению новых навыков</li>
          </ul>
        </div>
    </div>
    
  )
}

export default Home

// Angular/portfolio/src/app/home/home.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: 'home.component.html',
  styleUrls: ['home.component.css']
})
export class HomeComponent{ } 
<div class="backgroundMain">
    <div class="homeDiv">
      <img src="https://pic.rutubelist.ru/video/ec/0c/ec0c12ae7b425bd4055f9f0e16f3498e.jpg" alt="Portfolio Image" />
    </div>
    <div class="homeDiv">
      <a class="HeaderButton" href="https://github.com/DmitriyGorbulko/Portfolio">Ссылка на GitHub</a>
    </div>
    <div class="homeDiv">
      <ul class="homeUl">
        Навыки
        <li class="homeLi">Принципы SOLID</li>
        <li class="homeLi">Архитектура Onion</li>
        <li class="homeLi">Работа с различными реляционными БД</li>
        <li class="homeLi">Архитектура Onion</li>
        <li class="homeLi">Стремление к изучению новых навыков</li>
      </ul>
    </div>
  </div>
